git:
  parseEmoji: true
  # branchLogCmd: "git log --graph --color=always --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' {{branchName}} --"
  # allBranchesLogCmd: "git log --graph --color=always --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --all"

customCommands:
  - key: "<c-g>"
    context: "files"
    description: "commit files with format"
    prompts:
      - type: "menu"
        title: "What kind of commit type is it?"
        key: "Type"
        options:
          - name: "fix"
            description: "Fix bug and issues"
            value: "fix"
          - name: "feat"
            description: "Add new features"
            value: "feat"
          - name: "docs"
            description: "Update or improve documentation"
            value: "docs"
          - name: "style"
            description: "Code formatting fixes and UI Changes"
            value: "style"
          - name: "refactor"
            description: "Improve code without performance improvements"
            value: "refactor"
          - name: "test"
            description: "Add or improve tests"
            value: "test"
          - name: "perf"
            description: "Performance improvements"
            value: "perf"
          - name: "chore"
            description: "Changes and improvements to the build process"
            value: "chore"
          - name: "wip"
            description: "Work in progress"
            value: "wip"
      - type: "input"
        title: "Enter the Message"
        key: "Message"
        initialValue: ""
      - type: "menu"
        title: "Choise the emoji"
        key: "Emoji"
        options:
          - name: "(empty)"
            description: "Not using any emoji"
            value: ""
          - name: "Art"
            description: "ğŸ¨Improve structure / format of the code."
            value: ":art:"
          - name: "Zap"
            description: "âš¡ï¸Improve performance."
            value: ":zap:"
          - name: "Fire"
            description: "ğŸ”¥Remove code or files."
            value: ":fire:"
          - name: "Bug"
            description: "ğŸ›Fix a bug."
            value: ":bug:"
          - name: "Ambulance"
            description: "ğŸš‘Critical hotfix."
            value: ":ambulance:"
          - name: "Sparkles"
            description: "âœ¨Introduce new features."
            value: ":sparkles:"
          - name: "Memo"
            description: "ğŸ“Add or update documentation."
            value: ":memo:"
          - name: "Rocket"
            description: "ğŸš€Deploy stuff."
            value: ":rocket:"
          - name: "Lipstick"
            description: "ğŸ’„Add or update the UI and style files."
            value: ":lipstick:"
          - name: "Tada"
            description: "ğŸ‰Begin a project."
            value: ":tada:"
          - name: "White Check Mark"
            description: "âœ…Add, update, or pass tests."
            value: ":white_check_mark:"
          - name: "Lock"
            description: "ğŸ”’Fix security or privacy issues."
            value: ":lock:"
          - name: "Closed Lock With Key"
            description: "ğŸ”Add or update secrets."
            value: ":closed_lock_with_key:"
          - name: "Bookmark"
            description: "ğŸ”–Release / Version tags."
            value: ":bookmark:"
          - name: "Rotating Light"
            description: "ğŸš¨Fix compiler / linter warnings."
            value: ":rotating_light:"
          - name: "Construction"
            description: "ğŸš§Work in progress."
            value: ":construction:"
          - name: "Green Heart"
            description: "ğŸ’šFix CI Build."
            value: ":green_heart:"
          - name: "Arrow Down"
            description: "Downgrade dependencies."
            value: ":arrow_down:"
          - name: "Arrow Up"
            description: "Upgrade dependencies."
            value: ":arrow_up:"
          - name: "Pushpin"
            description: "ğŸ“Œ Pin dependencies to specific versions."
            value: ":pushpin:"
          - name: "Construction Worker"
            description: "ğŸ‘· Add or update CI build system."
            value: ":construction_worker:"
          - name: "Chart With Upwards Trend"
            description: "ğŸ“ˆ Add or update analytics or track code."
            value: ":chart_with_upwards_trend:"
          - name: "Recycle"
            description: "â™»ï¸Refactor code."
            value: ":recycle:"
          - name: "Heavy Plus Sign"
            description: "â• Add a dependency."
            value: ":heavy_plus_sign:"
          - name: "Heavy Minus Sign"
            description: "â– Remove a dependency."
            value: ":heavy_minus_sign:"
          - name: "Wrench"
            description: "ğŸ”§ Add or update configuration files."
            value: ":wrench:"
          - name: "Hammer"
            description: "ğŸ”¨ Add or update development scripts."
            value: ":hammer:"
          - name: "Globe With Meridians"
            description: "ğŸŒ Internationalization and localization."
            value: ":globe_with_meridians:"
          - name: "Pencil"
            description: "âœï¸ Fix typos."
            value: ":pencil2:"
          - name: "Poop"
            description: "ğŸ’© Write bad code that needs to be improved."
            value: ":poop:"
          - name: "Rewind"
            description: "âªï¸ Revert changes."
            value: ":rewind:"
          - name: "Twisted Rightwards Arrows"
            description: "ğŸ”€ Merge branches."
            value: ":twisted_rightwards_arrows:"
          - name: "Package"
            description: "ğŸ“¦ Add or update compiled files or packages."
            value: ":package:"
          - name: "Alien"
            description: "ğŸ‘½ Update code due to external API changes."
            value: ":alien:"
          - name: "Truck"
            description: "ğŸšš Move or rename resources (e.g.: files, paths, routes)."
            value: ":truck:"
          - name: "Page Facing Up"
            description: "ğŸ“„ Add or update license."
            value: ":page_facing_up:"
          - name: "Boom"
            description: "ğŸ’¥ Introduce breaking changes."
            value: ":boom:"
          - name: "Bento"
            description: "ğŸ± Add or update assets."
            value: ":bento:"
          - name: "Wheelchair"
            description: "â™¿ï¸ Improve accessibility."
            value: ":wheelchair:"
          - name: "Bulb"
            description: "ğŸ’¡ Add or update comments in source code."
            value: ":bulb:"
          - name: "Beers"
            description: "ğŸ» Write code drunkenly."
            value: ":beers:"
          - name: "Speech Balloon"
            description: "ğŸ’¬ Add or update text and literals."
            value: ":speech_balloon:"
          - name: "Card File Box"
            description: "ğŸ—ƒï¸ Perform database related changes."
            value: ":card_file_box:"
          - name: "Loud Sound"
            description: "ğŸ”Š Add or update logs."
            value: ":loud_sound:"
          - name: "Mute"
            description: "ğŸ”‡ Remove logs."
            value: ":mute:"
          - name: "Busts In Silhouette"
            description: "ğŸ‘¥ Add or update contributor(s)."
            value: ":busts_in_silhouette:"
          - name: "Children Crossing"
            description: "ğŸš¸ Improve user experience / usability."
            value: ":children_crossing:"
          - name: "Building Construction"
            description: "ğŸ—ï¸ Make architectural changes."
            value: ":building_construction:"
          - name: "Iphone"
            description: "ğŸ“± Work on responsive design."
            value: ":iphone:"
          - name: "Clown Face"
            description: "ğŸ¤¡ Mock things."
            value: ":clown_face:"
          - name: "Egg"
            description: "ğŸ¥š Add or update an easter egg."
            value: ":egg:"
          - name: "See No Evil"
            description: "ğŸ™ˆ Add or update a .gitignore file."
            value: ":see_no_evil:"
          - name: "Camera Flash"
            description: "ğŸ“¸ Add or update snapshots."
            value: ":camera_flash:"
          - name: "Alembic"
            description: "âš—ï¸ Perform experiments."
            value: ":alembic:"
          - name: "Mag"
            description: "ğŸ” Improve SEO."
            value: ":mag:"
          - name: "Label"
            description: "ğŸ·ï¸ Add or update types."
            value: ":label:"
          - name: "Seedling"
            description: "ğŸŒ± Add or update seed files."
            value: ":seedling:"
          - name: "Triangular Flag On Post"
            description: "ğŸš© Add, update, or remove feature flags."
            value: ":triangular_flag_on_post:"
          - name: "Goal Net"
            description: "ğŸ¥… Catch errors."
            value: ":goal_net:"
          - name: "Dizzy"
            description: "ğŸ’« Add or update animations and transitions."
            value: ":dizzy:"
          - name: "Wastebasket"
            description: "ğŸ—‘ï¸ Deprecate code that needs to be cleaned up."
            value: ":wastebasket:"
          - name: "Passport Control"
            description: "ğŸ›‚ Work on code related to authorization, roles and permissions."
            value: ":passport_control:"
          - name: "Adhesive Bandage"
            description: "ğŸ©¹ Simple fix for a non-critical issue."
            value: ":adhesive_bandage:"
          - name: "Monocle Face"
            description: "ğŸ§ Data exploration/inspection."
            value: ":monocle_face:"
          - name: "Coffin"
            description: "âš°ï¸ Remove dead code."
            value: ":coffin:"
          - name: "Test Tube"
            description: "ğŸ§ª Add a failing test."
            value: ":test_tube:"
          - name: "Necktie"
            description: "ğŸ‘” Add or update business logic."
            value: ":necktie:"
          - name: "Stethoscope"
            description: "ğŸ©º Add or update healthcheck."
            value: ":stethoscope:"
          - name: "Bricks"
            description: "ğŸ§± Infrastructure related changes."
            value: ":bricks:"
          - name: "Technologist"
            description: "ğŸ§‘â€ğŸ’» Improve developer experience."
            value: ":technologist:"
          - name: "Money With Wings"
            description: "ğŸ’¸ Add sponsorships or money related infrastructure."
            value: ":money_with_wings:"
          - name: "Thread"
            description: "ğŸ§µ Add or update code related to multithreading or concurrency."
            value: ":thread:"
          - name: "Safety Vest"
            description: "ğŸ¦º Add or update code related to validation."
            value: ":safety_vest:"
      - type: "confirm"
        title: "Commit"
        body: "Commit with the message '{{.Form.Type}}: {{.Form.Emoji}}{{.Form.Message}}'. Is this okay?"
    command: 'bash -c ''type="{{.Form.Type}}"; message="{{.Form.Message}}"; emoji="{{.Form.Emoji}}"; commit_message="$type: $emoji $message"; git commit -m "$commit_message"'''
    loadingText: "Commiting..."
